import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { JSX } from 'react';

export default function App({ Component, pageProps }: AppProps): JSX.Element {
  return <>
		<Head>
        <title>Create Next</title>
        <meta name="description" content="Generated by create next" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link key={1} rel="icon" href="/favicon_2.ico" />
      </Head>
		<Component {...pageProps} />;
	</>
}
